### ISSUE TITLE
Support for multiple tables

### ISSUE THREAD

**Issue by ryanblock** [alexdebrie/serverless-dynamodb-backups#1]
This is dope! Simple, elegant, and the Slack support is a nice touch! 👌

Re. multiple tables mention in readme:
> Multiple tables? Currently you would need to deploy a separate service for each table you want to back up. A future solution have a file that lists all tables to be backed up.

Opening an issue as this would be a great improvement.

We have a few dozen tables we'd love to run this against. It's definitely feasible as-is, just not nearly as desirable to run / maintain dozens of individual functions.

**Comment by alexdebrie** [comment]
Thanks, @ryanblock! That's good to know that the multiple table option would be helpful. I'll try to take a look at this soon 😄

**Comment by alexdebrie** [comment]
EDIT: This is now implemented in #2. Take a look at the [Configuration section](https://github.com/alexdebrie/serverless-dynamodb-backups/blob/59f4e5b44acc0fabcfeee93864755e28ff8a167e/README.md#configuration) of the README for a walkthrough. Curious to hear your thoughts.

@ryanblock Just had a thought -- would you prefer a list to specify tables to backup, or would be it be better to specify a regex that would be matched against a `ListTables` call? This way you wouldn't have to redeploy the service every time you added a new table.

For example, if you had the following tables in DynamoDB:

- `prod-UsersTable`
- `dev-UsersTable`
- `prod-ProductsTable`
- `stage-ProductsTable`
- `dev-ProductsTable`

You could specify `tablePattern: '^(prod-|stage-)'` to indicate that you only want to backup your Prod and Stage tables. This would require `dynamodb:ListTables` permissions for the Lambda function.

Perhaps all three methods (regex, file list, single table) based on the config that is passed?

**Comment by ryanblock** [comment]
Yo, just saw you patched this, right on!

Was going to say that a simple list would prob be the easiest first step in that direction before implementing more powerful regex-based table matching, but it looks like you took care of both cases! 👏👏👏
